### ISSUE TITLE
فونت mitra.woff

### ISSUE THREAD

**Issue by rastikerdar** [m-kafiyan/green-web---oxin#1]
با سلام.
آیا این نسخه از فونت میترا که در پروژه قرار دادید برای استفاده عموم آزاد است؟ از این رو آن را می پرسم که با نسخه اصلی آن اندکی تفاوت دارد.

با تشکر

**Comment by m-kafiyan** [comment]
@rastikerdar
سلام
بله میتونید از این فونت استفاده کنید.

**Comment by rastikerdar** [comment]
ممنون از پاسختون
